version: "2"


#---------------JENKINS------------------
services:
  jenkins:
    container_name: jenkins
    image: jenkins_project
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - JAVA_OPTS:-Djava.awt.headless=true
    restart: always

#--------------SONARQUBE-----------------
  sonarqube:
    container_name: sonarqube
    image: sonarqube_project
    ports:
      - 9000:9000
    links:
        - db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    restart: always

  db:
    container_name: sonarqube_db
    image: sonarqube_db_project
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
    restart: always
#-------------------MANTIS-------------------
  mantisbt:
    container_name: mantis
    image: mantis_project
    ports:
     - 8989:80
    links:
     - mysql
    restart: always

  mysql:
    container_name: mantis_db
    image: mantis_db_project
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always
#-----------------TESTLINK-------------------
  mariadb:
    container_name: testlink_mariadb
    image: bitnami/mariadb 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_testlink
      - MARIADB_DATABASE=bitnami_testlink
    volumes:
      - mariadb_data:/bitnami
    restart: always
  
  testlink:
    container_name: testlink
    image: testlink_project
    ports:
      - 80:80
      - 443:443
    volumes:
      - testlink_data:/bitnami
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - TESTLINK_DATABASE_USER=bn_testlink
      - TESTLINK_DATABASE_NAME=bitnami_testlink
      - ALLOW_EMPTY_PASSWORD=yes
      - TESTLINK_USERNAME=admin
      - TESTLINK_PASSWORD=root
      - TESTLINK_EMAIL=admin@example.com
    restart: always
#-------------------------MYSQL-PROJECT----------------------
  mysql_project:
    container_name: mysql
    image: mysql_project
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    restart: always
#------------------------Tomcat-----------------------------
  tomcat:
    container_name: tomcat
    image: tomcat_project
    ports:
      - 8888:8080
    restart: always



volumes:
  jenkins_data:
    driver: local
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  mariadb_data:
    driver: local
  testlink_data:
    driver: local
  testlink_data:
    driver: local
